//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGestionTiendaAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.UsuariosTienda = new HashSet<UsuariosTienda>();
        }
    
        public int Id_Cliente { get; set; }
        public string Nombre { get; set; }
        public string CorreoElectronico { get; set; }
        public string Clave { get; set; }
        public string ConfirmacionClave { get; set; }
        public bool Activo { get; set; }
        public int IdRol { get; set; }
    
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosTienda> UsuariosTienda { get; set; }
    }
}
